name: Pets
version: ${project.version}
main: gg.steve.elemental.pets.Pets
api-version: 1.13
authors: [stevegoodhill]
description: Pets plugin developed for ElementalMC.
commands:
  pet:
    usage: /<command>
    description: Base commands for elemental pets.
    aliases:
      - pets